name: OWASP ZAP DAST Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Run App Container
        run: |
          docker build -t zap-demo-app .
          docker run -d -p 5001:5000 zap-demo-app
          sleep 5  # Give container time to start

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap_results
          chmod 777 zap_results
          
          docker run --name zap_scan --network="host" \
            -u 0 \
            -v $(pwd)/zap_results:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:5001 \
            -r zap_report.html \

          EXIT_CODE=$(docker inspect zap_scan --format='{{.State.ExitCode}}')

          docker cp zap_scan:/zap/zap_report.html ./zap_results/zap_report.html || true
          docker rm zap_scan || true
          
          echo "ZAP exit code: $EXIT_CODE"
          if [ "$EXIT_CODE" -ne 0 ]; then
            echo "❌ ZAP scan found issues. Failing the job."
            exit 1
          fi

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: zap_results/zap_report.html
